### ISSUE TITLE
Support mapping classes via interface (repository, dao)

### ISSUE THREAD

**Issue by mishak87** [Kdyby/Doctrine#41]
_This behavior is not implemented in Doctrine. I think it could enable richer modularity. I reserve the right to be dead wrong._

Using [RTEL](http://docs.doctrine-project.org/en/latest/cookbook/resolve-target-entity-listener.html) relations can be declared using interfaces without knowing class of implementation.

Application of this approach reaches dead end when using entity.dao factory or EntityManager::getRepository or alias getDao in code. Basically reaching for repository using interface is not supported. _Reasoning: Whole extensions and models can get away without knowing class name of actual implementation, using interface should allow more room._
## Roadmap
- [x] Implement RTEL part of #40 (extension interface and configuration)
- [x] _Hashmap_ will be extracted from RTEL configuration as `[ interface => configuration ]`
  _(not including mapping information)_
- [x] Add last parameter to EM constructor/create with _hashmap_.
- [x] Override getClassMetadata to check _hashmap_ before checking class existence

Note: _Solution should not be limited to only one interface per class._
